### ISSUE TITLE
Errror while installing requirement.txt

### ISSUE THREAD

**Issue by shfaizan** [jczestochowska/heartbeat_classification#12]
Hi 
I am getting error in installing the requirement.txt file 
when I do `pip install -r requirements.txt` I got the error after MarkSafe==1.0 and this is the error I get:
`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`
I am using Windows 10 
python 3.8, Cuda 10.1, 10.2

**Comment by jczestochowska** [comment]
Hi @shfaizan, I updated the `requirements.txt` the problem should be fixed now
